"""product and warehouse upgrade

Revision ID: 3984af08faf6
Revises: fff9128cf3d7
Create Date: 2026-03-03 14:24:43.905985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3984af08faf6'
down_revision: Union[str, Sequence[str], None] = 'fff9128cf3d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_fragile', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('is_perishable', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('min_order_quantity', sa.Integer(), nullable=True))
    op.add_column('warehouses', sa.Column('operational_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('warehouses', 'operational_status')
    op.drop_column('products', 'min_order_quantity')
    op.drop_column('products', 'is_perishable')
    op.drop_column('products', 'is_fragile')
    # ### end Alembic commands ###
